version: "3.8"

services:
  backend:
    build: .
    restart: always
    networks:
      data-station-network:
        ipv4_address: 172.20.14.97

networks:
  data-station-network:
    external: true
