version: "3.8"

services:
  localwisdom_backend:
    build: .
    pull_policy: build
    container_name: localwisdom-backend
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    ports:
      - "5050:5050"
    restart: always
    command: gunicorn app:app --bind 0.0.0.0:5050
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.135

networks:
  nginx-manager_customnetwork:
    external: true
